# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oi35Xl0BTR-L3D6ohliqaii4WeO5MJOJ
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
df=pd.read_csv('/content/mall_customers.csv')
print("first five data",df.head())
print("shape of data",df.shape)
print("nature of data",df.info())
print("summary",df.describe())
print("null value detection",df.isnull().sum())
x=df[["CustomerID","Annual Income (k$)","Age"]]
sum_squared_distances=[]
k_values=range(1,11)
for k in k_values:
  kmeans=KMeans(n_clusters=k,random_state=42)
  kmeans.fit(x)
  sum_squared_distances.append(kmeans.inertia_)
plt.plot(k_values,sum_squared_distances,marker='*')
plt.xlabel("number of clusters")
plt.ylabel("sum of squared distances")
plt.title("kmeans clustring")
plt.show()