# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
S = pd.Series([1, 2, 3, 4, 5])
B = pd.Series([2, 4, 6, 8, 10])

M = S[S.isin(B)]
print(M)

import matplotlib.pyplot as plt
df=pd.read_csv('/content/mtcars (1).csv')
plt.hist(df['mpg'])
plt.xlabel('miles per gallon')
plt.ylabel('frequency')
plt.title('HISTOGRAM')
plt.show()

import matplotlib.pyplot as plt
df=pd.read_csv('/content/mtcars (1).csv')
plt.scatter(df['wt'],df['mpg'])
plt.xlabel('Cars')
plt.ylabel('weight')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('/content/mtcars (1).csv')
trans=(df['am'].value_counts())
trans.plot(kind='bar')
plt.xlabel('Type')
plt.ylabel('frequency')
plt.title('frequency distribution')
plt.show()

import matplotlib.pyplot as plt
df=pd.read_csv('/content/mtcars (1).csv')
plt.boxplot(df['mpg'])
plt.title('boxplot')
plt.xlabel('height')
plt.ylabel('Frequency')
plt.show()