# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
df=pd.read_csv('/content/mall_customers.csv')
x=df[["CustomerID","Annual Income (k$)","Age"]]
sum_squared_distances=[]
k_values=range(1,11)
for k in k_values:
  kmeans=KMeans(n_clusters=k,random_state=42)
  kmeans.fit(x)
  sum_squared_distances.append(kmeans.inertia_)
plt.plot(k_values,sum_squared_distances,marker='o')
plt.xlabel("number of clusters")
plt.ylabel("sum squared distances")
plt.title("k_means clustring")
plt.show()